[workspace]
members = [
    "rusty_weel",
    "rusty_weel_macro",
    "http_helper"
]

package.include = ["/resources"]
workspace.resolver = "2"


[profile.release]
strip = true # Strips symbols from the binary
opt-level = "z" #optimize for size
lto = true # Link time optimization
panic = "abort"
codegen-units = 1
