[workspace]

members = [
    "weel_bin",
    "weel_inject",
    "weel_lib_wrapper",
    "weel_lib"
]

[profile.release]
strip = false # Strips symbols from the binary
opt-level = "z" #optimize for size
lto = false # Link time optimization
codegen-units = 16
incremental = true
resolver = "1"