[package]
name = "http_helper"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = "0.12.5"
log = "0.4.21"
base64 = "0.22.1"
multipart = "0.18.0"
tempfile = "3.10.1"
derive_more = "0.99.18"
mime = "0.3.17"