[package]
name = "weel_lib_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "weel_lib_wrapper"
path = "src/lib.rs"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weel_lib ={ path = "../weel_lib"}
